"""empty message

Revision ID: f9f8605a5cf1
Revises: 5b4977de2225
Create Date: 2024-06-20 14:20:43.964364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f8605a5cf1'
down_revision = '5b4977de2225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'])
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###
