"""empty message

Revision ID: fdf8a84ccb4f
Revises: 29b132d97862
Create Date: 2024-07-29 11:17:28.815099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf8a84ccb4f'
down_revision = '29b132d97862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint('videos_game_id_fkey', type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('videos_game_id_fkey', 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###
